# Posizione e dimensioni
anchor = bottom center
margin = 0 0 120 0
width = 300
height = 40
orientation = horizontal
border_offset = 1
max = 100

# Aspetto generale
background_color = 000000ff
border_color = cba135ff
border_size = 2

# Barra di progresso
bar_color = ffffffff
bar_padding = 3

# Timeout
timeout = 800

[style.muted]
background_color = 000000ff
border_color = ffffffff
bar_color = cba135ff
